apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
spec:
  finalizers:
    - kubernetes
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: kube-system
spec:
  chart: metallb
  repo: https://metallb.github.io
  targetNamespace: metallb-system
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: unifi-os-server-vip-ipaddresspool
  namespace: metallb-system
spec:
  addresses:
    - 10.0.0.11/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: unifi-os-server-vip-l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - unifi-os-server-vip-ipaddresspool
