apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-os-server-pvc
  namespace: unifi
spec:
  storageClassName: harvester
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 32Gi
